/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.paipeng.sudoku4x4;

import org.junit.Test;
import static org.junit.Assert.*;

public class Sudoku4x4GenTest {
    @Test public void testSomeLibraryMethod() {
        Sudoku4x4Gen classUnderTest = new Sudoku4x4Gen();
        classUnderTest.test();
        //assertTrue("someLibraryMethod should return 'true'", ;);
    }
}
